Repository rohan-singh-rajput/Chat-App, pull requests merged in 2022-10, with the labels that each got.

#2 JavaNetCookieJar convert to kotlin
  app/src/main/java/com/example/chatapp/di/NetworkModule.kt
  app/src/main/java/com/example/chatapp/util/JavaNetCookieJar.java
  app/src/main/java/com/example/chatapp/util/JavaNetCookieJar.kt
Labels: enhancement, hacktoberfest, HACKTOBERFEST-ACCEPTED

#3 update readme
  README.md
Labels: documentation, hacktoberfest, HACKTOBERFEST-ACCEPTED

#4 single modifier instance for entire function module add
  .gradle/7.4/executionHistory/executionHistory.bin
  .gradle/7.4/executionHistory/executionHistory.lock
  .gradle/7.4/fileHashes/fileHashes.bin
  .gradle/7.4/fileHashes/fileHashes.lock
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .idea/inspectionProfiles/Project_Default.xml
  app/src/main/java/com/example/chatapp/presentation/components/chat/chat_item/ChatItem.kt
  app/src/main/java/com/example/chatapp/presentation/components/login_signup/Login.kt
  app/src/main/java/com/example/chatapp/presentation/components/login_signup/Signup.kt
Labels: enhancement, hacktoberfest, HACKTOBERFEST-ACCEPTED

#5 Dev
  .gradle/7.4/executionHistory/executionHistory.bin
  .gradle/7.4/executionHistory/executionHistory.lock
  .gradle/7.4/fileHashes/fileHashes.bin
  .gradle/7.4/fileHashes/fileHashes.lock
  .gradle/7.4/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  app/src/main/java/com/example/chatapp/di/NetworkModule.kt
  app/src/main/java/com/example/chatapp/presentation/components/Home.kt
  app/src/main/java/com/example/chatapp/presentation/components/chat/chat_list/ChatList.kt
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED
